import type { BulkAdapterDefinition } from '../types/bulk-ingestion.types.js';

const BUILT_IN_TIMESTAMP = new Date(0).toISOString();

export const BUILT_IN_BULK_ADAPTER_DEFINITIONS: BulkAdapterDefinition[] = [
  {
    id: 'bulk-adapter-definition:built-in:bridge-standard',
    type: 'bulk-adapter-definition',
    tenantId: 'system',
    adapterKey: 'bridge-standard',
    name: 'Bridge Standard',
    description: 'Standard Bridge CSV/XLSX package with one mapped appraisal PDF per row.',
    matchMode: 'EXACT',
    sourceAdapter: 'bridge-standard',
    requiredAnyOf: [
      {
        sources: ['item.source.loanNumber', 'item.source.externalId'],
        code: 'BRIDGE_ID_REQUIRED',
        messageTemplate: "bridge-standard requires loanNumber or externalId (item '{itemId}')",
      },
    ],
    documentRequirement: {
      required: true,
      code: 'BRIDGE_DOCUMENT_REQUIRED',
      messageTemplate: "bridge-standard requires mapped document blob for item '{itemId}'",
    },
    canonicalFieldMappings: [
      { targetField: 'correlationKey', source: 'item.correlationKey' },
      { targetField: 'loanNumber', source: 'item.source.loanNumber' },
      { targetField: 'externalId', source: 'item.source.externalId' },
      { targetField: 'propertyAddress', source: 'item.source.propertyAddress' },
      { targetField: 'dataFileBlobName', source: 'job.dataFileBlobName' },
    ],
    isBuiltIn: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: 'bulk-adapter-definition:built-in:bpo-report-v1',
    type: 'bulk-adapter-definition',
    tenantId: 'system',
    adapterKey: 'bpo-report-v1',
    name: 'BPO Report v1',
    description: 'Residential BPO package with one mapped PDF report per row.',
    matchMode: 'EXACT',
    sourceAdapter: 'bpo-report-v1',
    documentRequirement: {
      required: true,
      code: 'BPO_DOCUMENT_REQUIRED',
      messageTemplate: "bpo-report-v1 requires document blob mapping for item '{itemId}'",
    },
    canonicalFieldMappings: [
      { targetField: 'correlationKey', source: 'item.correlationKey' },
      { targetField: 'propertyAddress', source: 'item.source.propertyAddress' },
      { targetField: 'externalId', source: 'item.source.externalId' },
    ],
    staticCanonicalData: {
      bpoDocumentType: 'BPO_REPORT',
    },
    isBuiltIn: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: 'bulk-adapter-definition:built-in:statebridge',
    type: 'bulk-adapter-definition',
    tenantId: 'system',
    adapterKey: 'statebridge',
    name: 'Statebridge',
    description: 'Statebridge appraisal package; supports exact keys and run-id suffixed variants.',
    matchMode: 'PREFIX',
    sourceAdapter: 'statebridge',
    requiredAnyOf: [
      {
        sources: ['item.source.loanNumber', 'item.source.externalId'],
        code: 'STATEBRIDGE_ID_REQUIRED',
        messageTemplate: "statebridge requires loanNumber or externalId (item '{itemId}')",
      },
    ],
    documentRequirement: {
      required: true,
      code: 'STATEBRIDGE_DOCUMENT_REQUIRED',
      messageTemplate: "statebridge requires mapped document blob for item '{itemId}'",
    },
    canonicalFieldMappings: [
      { targetField: 'correlationKey', source: 'item.correlationKey' },
      { targetField: 'loanNumber', source: 'item.source.loanNumber' },
      { targetField: 'externalId', source: 'item.source.externalId' },
      { targetField: 'propertyAddress', source: 'item.source.propertyAddress' },
      { targetField: 'dataFileBlobName', source: 'job.dataFileBlobName' },
    ],
    isBuiltIn: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: 'bulk-adapter-definition:built-in:tape-conversion-v1',
    type: 'bulk-adapter-definition',
    tenantId: 'system',
    adapterKey: 'tape-conversion-v1',
    name: 'Tape Conversion v1',
    description: 'Spreadsheet-only conversion flow without supporting PDFs.',
    matchMode: 'EXACT',
    sourceAdapter: 'tape-conversion-v1',
    requiredAnyOf: [
      {
        sources: ['item.source.loanNumber', 'item.source.externalId'],
        code: 'TAPE_CONVERSION_ID_REQUIRED',
        messageTemplate: "tape-conversion-v1 requires loanNumber or externalId (item '{itemId}')",
      },
    ],
    requiredFields: [
      {
        source: 'item.source.propertyAddress',
        code: 'TAPE_CONVERSION_ADDRESS_REQUIRED',
        messageTemplate: "tape-conversion-v1 requires propertyAddress (item '{itemId}')",
      },
    ],
    canonicalFieldMappings: [
      { targetField: 'correlationKey', source: 'item.correlationKey' },
      { targetField: 'loanNumber', source: 'item.source.loanNumber' },
      { targetField: 'externalId', source: 'item.source.externalId' },
      { targetField: 'propertyAddress', source: 'item.source.propertyAddress' },
      { targetField: 'city', source: 'item.source.city' },
      { targetField: 'state', source: 'item.source.state' },
      { targetField: 'zipCode', source: 'item.source.zipCode' },
    ],
    isBuiltIn: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: 'bulk-adapter-definition:built-in:generic-appraisal-v1',
    type: 'bulk-adapter-definition',
    tenantId: 'system',
    adapterKey: 'generic-appraisal-v1',
    name: 'Generic Appraisal v1',
    description: 'Generic appraisal report package for clients that only need loan identity plus a mapped PDF.',
    matchMode: 'EXACT',
    sourceAdapter: 'generic-appraisal-v1',
    requiredAnyOf: [
      {
        sources: ['item.source.loanNumber', 'item.source.externalId'],
        code: 'GENERIC_APPRAISAL_ID_REQUIRED',
        messageTemplate: "generic-appraisal-v1 requires loanNumber or externalId (item '{itemId}')",
      },
    ],
    requiredFields: [
      {
        source: 'item.source.propertyAddress',
        code: 'GENERIC_APPRAISAL_ADDRESS_REQUIRED',
        messageTemplate: "generic-appraisal-v1 requires propertyAddress (item '{itemId}')",
      },
    ],
    documentRequirement: {
      required: true,
      code: 'GENERIC_APPRAISAL_DOCUMENT_REQUIRED',
      messageTemplate: "generic-appraisal-v1 requires mapped document blob for item '{itemId}'",
    },
    canonicalFieldMappings: [
      { targetField: 'correlationKey', source: 'item.correlationKey' },
      { targetField: 'loanNumber', source: 'item.source.loanNumber' },
      { targetField: 'externalId', source: 'item.source.externalId' },
      { targetField: 'propertyAddress', source: 'item.source.propertyAddress' },
      { targetField: 'city', source: 'item.source.city' },
      { targetField: 'state', source: 'item.source.state' },
      { targetField: 'zipCode', source: 'item.source.zipCode' },
      { targetField: 'dataFileBlobName', source: 'job.dataFileBlobName' },
    ],
    isBuiltIn: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: 'bulk-adapter-definition:built-in:fnma-1004-v1',
    type: 'bulk-adapter-definition',
    tenantId: 'system',
    adapterKey: 'fnma-1004-v1',
    name: 'FNMA 1004 v1',
    description: 'Uniform Residential Appraisal Report package aligned to FNMA 1004 uploads.',
    matchMode: 'EXACT',
    sourceAdapter: 'fnma-1004-v1',
    requiredAnyOf: [
      {
        sources: ['item.source.loanNumber', 'item.source.externalId'],
        code: 'FNMA_1004_ID_REQUIRED',
        messageTemplate: "fnma-1004-v1 requires loanNumber or externalId (item '{itemId}')",
      },
    ],
    requiredFields: [
      {
        source: 'item.source.propertyAddress',
        code: 'FNMA_1004_ADDRESS_REQUIRED',
        messageTemplate: "fnma-1004-v1 requires propertyAddress (item '{itemId}')",
      },
    ],
    documentRequirement: {
      required: true,
      code: 'FNMA_1004_DOCUMENT_REQUIRED',
      messageTemplate: "fnma-1004-v1 requires mapped document blob for item '{itemId}'",
    },
    canonicalFieldMappings: [
      { targetField: 'correlationKey', source: 'item.correlationKey' },
      { targetField: 'loanNumber', source: 'item.source.loanNumber' },
      { targetField: 'externalId', source: 'item.source.externalId' },
      { targetField: 'propertyAddress', source: 'item.source.propertyAddress' },
      { targetField: 'city', source: 'item.source.city' },
      { targetField: 'state', source: 'item.source.state' },
      { targetField: 'zipCode', source: 'item.source.zipCode' },
      { targetField: 'propertyType', source: 'item.source.propertyType' },
      { targetField: 'loanAmount', source: 'item.source.loanAmount' },
      { targetField: 'loanPurpose', source: 'item.source.loanPurpose' },
      { targetField: 'occupancyType', source: 'item.source.occupancyType' },
      { targetField: 'dataFileBlobName', source: 'job.dataFileBlobName' },
    ],
    staticCanonicalData: {
      appraisalForm: 'FNMA_1004',
    },
    isBuiltIn: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: 'bulk-adapter-definition:built-in:residential-bpo-v2',
    type: 'bulk-adapter-definition',
    tenantId: 'system',
    adapterKey: 'residential-bpo-v2',
    name: 'Residential BPO v2',
    description: 'Second-generation residential BPO package with mapped PDF report and address-level validation.',
    matchMode: 'EXACT',
    sourceAdapter: 'residential-bpo-v2',
    requiredFields: [
      {
        source: 'item.source.propertyAddress',
        code: 'RESIDENTIAL_BPO_ADDRESS_REQUIRED',
        messageTemplate: "residential-bpo-v2 requires propertyAddress (item '{itemId}')",
      },
    ],
    documentRequirement: {
      required: true,
      code: 'RESIDENTIAL_BPO_DOCUMENT_REQUIRED',
      messageTemplate: "residential-bpo-v2 requires mapped document blob for item '{itemId}'",
    },
    canonicalFieldMappings: [
      { targetField: 'correlationKey', source: 'item.correlationKey' },
      { targetField: 'propertyAddress', source: 'item.source.propertyAddress' },
      { targetField: 'externalId', source: 'item.source.externalId' },
      { targetField: 'city', source: 'item.source.city' },
      { targetField: 'state', source: 'item.source.state' },
      { targetField: 'zipCode', source: 'item.source.zipCode' },
    ],
    staticCanonicalData: {
      bpoDocumentType: 'RESIDENTIAL_BPO',
    },
    isBuiltIn: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
];