/**
 * Construction Finance Module — Construction Status Report Types (AI Pillar 3)
 *
 * ConstructionStatusReport documents are auto-generated by the AI Servicing layer
 * on a configurable schedule (default: monthly) and on-demand / on CPP trigger.
 * They provide a snapshot of loan health, AI-generated narrative commentary,
 * and recommended actions for loan administrators.
 *
 * Stored in the `construction-loans` Cosmos container (partition key: /tenantId).
 */

import type { ConstructionRiskFlag } from './construction-risk.types.js';

// ─── Construction Status Report ───────────────────────────────────────────────

export interface ConstructionStatusReport {
  id: string;
  constructionLoanId: string;
  tenantId: string;

  /** ISO date the report covers (typically today for on-demand; scheduled date for cron-generated). */
  reportDate: string;

  /**
   * What triggered this report:
   * SCHEDULED    — auto-generated by the servicing cron per statusReportFrequencyDays
   * ON_DEMAND    — triggered manually by a loan admin or lender
   * CPP          — triggered by a CPP_TRIGGER risk flag firing
   * MATURITY_ALERT — triggered by MATURITY_APPROACHING flag
   */
  reportType: 'SCHEDULED' | 'ON_DEMAND' | 'CPP' | 'MATURITY_ALERT';

  /** Whether this report was generated by the AI service or authored/edited by a human. */
  generatedBy: 'AI_AUTO' | 'HUMAN';

  // ── AI-Generated Narrative ────────────────────────────────────────────────
  /**
   * AI-generated summary paragraph suitable for inclusion in lender investor reports
   * or warehouse line communications.  One concise paragraph, factual, no jargon.
   */
  summary: string;

  // ── Progress Snapshot ─────────────────────────────────────────────────────
  /** Inspector-certified overall project completion percentage at the time of this report. */
  percentComplete: number;

  /**
   * AI model P50 (median) estimated completion date.
   * ISO date string.
   */
  completionForecastP50: string;

  /**
   * AI model P75 (75th percentile — pessimistic) estimated completion date.
   * If P75 > maturityDate − maturityWarningDays, MATURITY_APPROACHING fires.
   * ISO date string.
   */
  completionForecastP75: string;

  /** Days remaining until loan maturityDate as of reportDate. */
  daysToMaturity: number;

  // ── Budget Snapshot ───────────────────────────────────────────────────────
  budgetSnapshot: {
    totalBudget: number;
    totalDrawnToDate: number;
    totalRemainingBudget: number;
    contingencyRemaining: number;
    retainageHeld: number;
  };

  // ── Risk Flags ────────────────────────────────────────────────────────────
  /** All currently active (unresolved) risk flags on this loan at the time of this report. */
  activeRiskFlags: ConstructionRiskFlag[];

  // ── Pending Items ─────────────────────────────────────────────────────────
  /** Number of draw requests in SUBMITTED / INSPECTION_ORDERED / UNDER_REVIEW / APPROVED state. */
  pendingDraws: number;

  /** Number of draw inspections in SCHEDULED / IN_PROGRESS state. */
  pendingInspections: number;

  /** Number of draws with lienWaiverStatus = PENDING. */
  pendingLienWaivers: number;

  /** Number of change orders in SUBMITTED / UNDER_REVIEW state. */
  pendingChangeOrders: number;

  // ── AI Insights & Actions ─────────────────────────────────────────────────
  /**
   * AI-generated bullet-point observations about this loan's health.
   * e.g. "Budget burn rate is tracking ahead of schedule by 8%",
   *       "GC license expires in 22 days — renewal verification required"
   */
  narrativeInsights: string[];

  /**
   * AI-suggested next steps for the loan administrator.
   * e.g. "Order draw inspection before processing Draw 4",
   *       "Initiate extension discussion — P75 forecast exceeds maturity by 18 days"
   */
  recommendedActions: string[];

  createdAt: string;
}
