/**
 * Final Report Generation Types
 * Phase 7: Final Delivery & Completion
 */

// ===========================
// ENUMS
// ===========================

export enum FinalReportStatus {
  PENDING    = 'PENDING',
  GENERATING = 'GENERATING',
  GENERATED  = 'GENERATED',
  FAILED     = 'FAILED'
}

// ===========================
// FIELD OVERRIDES & REVIEWER EDITS
// ===========================

/**
 * A single field-level correction made by a QC reviewer.
 * Stored on the QCReview document; merged into the PDF fill map at generation time.
 * Override values always win over source data.
 */
export interface FieldOverride {
  /** PDF AcroForm field key, e.g. "appraiserOpinionOfValue" */
  fieldKey: string;
  /** The value as it appeared in the original appraisal data */
  originalValue: string;
  /** The corrected value to use in the final report */
  overrideValue: string;
  /** userId of the person who made the override */
  overriddenBy: string;
  /** ISO 8601 date string */
  overriddenAt: string;
  /** Optional prose explanation — written by a human or generated by AI */
  narrativeComment?: string;
  source: 'HUMAN' | 'AI';
}

/**
 * A longer-form narrative edit attached to a review.
 * May reference a specific FieldOverride (fieldOverrideId) or be free-standing (e.g. a section narrative).
 */
export interface ReviewerEdit {
  id: string;
  reviewId: string;
  /** Optional link to a specific FieldOverride */
  fieldOverrideId?: string;
  /** High-level section, e.g. 'COMP_ANALYSIS' | 'RECONCILIATION' | 'NARRATIVE' | 'GENERAL' */
  section: string;
  narrativeComment: string;
  source: 'HUMAN' | 'AI';
  createdBy: string;
  /** ISO 8601 date string */
  createdAt: string;
}

// ===========================
// FINAL REPORT RECORD
// ===========================

/**
 * Embedded in the `orders` document as `order.finalReports[]`.
 * Each element represents one generation attempt (GENERATING → GENERATED | FAILED).
 * Sorted by createdAt descending when read; the first element is the most-recent attempt.
 */
export interface FinalReport {
  id: string;
  tenantId: string;
  orderId: string;
  qcReviewId: string;

  // Template used
  templateId: string;
  templateName: string;
  /** e.g. 'FORM_1004', 'FORM_2055' — from AppraisalFormType enum */
  formType: string;

  status: FinalReportStatus;

  // Blob storage
  /** e.g. orders/{orderId}/final-reports/{id}.pdf */
  blobPath?: string;
  /** Publicly accessible or SAS URL */
  blobUrl?: string;

  // Reviewer corrections applied during generation
  fieldOverrides: FieldOverride[];
  reviewerEdits: ReviewerEdit[];

  // Generation metadata
  generatedBy: string;
  /** ISO 8601 — set when status becomes GENERATED */
  generatedAt?: string;
  failureReason?: string;

  // Post-generation event chain flags
  mismoQueued: boolean;
  /** Blob path of the generated MISMO XML, e.g. orders/{orderId}/mismo/{id}.xml — set after successful MISMO generation */
  mismoXmlBlobPath?: string;
  underwritingQueued: boolean;

  createdAt: string;
  updatedAt: string;
}

// ===========================
// REQUEST / RESPONSE TYPES
// ===========================

export interface FinalReportGenerationRequest {
  orderId: string;
  templateId: string;
  requestedBy: string;
  notes?: string;
  /**
   * Base64-encoded custom addendum page PDFs (jsPDF output from frontend).
   * Each entry is appended after the last filled URAR page in array order.
   * Example sources: photo addendum, market condition addendum, location map.
   */
  customPagePdfs?: string[];
}

/**
 * Metadata for one available report template.
 * Derived from listing the `pdf-report-templates` Blob container.
 */
export interface ReportTemplate {
  /** Unique identifier — typically the blobName without extension */
  id: string;
  /** Human-readable name, e.g. "Form 1004 — Uniform Residential Appraisal Report" */
  name: string;
  /** Appraisal form type, e.g. 'FORM_1004' */
  formType: string;
  /** Blob filename, e.g. "DVR_1_Value_NonOwner_Occupied_Desk_Review_10-template.pdf" */
  blobName: string;
  description?: string;
  isActive: boolean;
}
