/**
 * Seed Module: PDF Templates
 *
 * Seeds a document-template metadata record and, when a storage account is
 * available, builds a Form 1004 AcroForm PDF using pdf-lib and uploads it
 * to Azure Blob Storage.
 * Container: document-templates (partition /tenantId)
 * Blob container: pdf-report-templates
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { BlobServiceClient } from '@azure/storage-blob';
import { DefaultAzureCredential } from '@azure/identity';
import type { SeedModule, SeedModuleResult, SeedContext } from '../seed-types.js';
import { upsert, cleanContainer, daysAgo } from '../seed-types.js';
import { PDF_TEMPLATE_IDS } from '../seed-ids.js';

const CONTAINER = 'document-templates';
const BLOB_CONTAINER = 'pdf-report-templates';
const TEMPLATE_BLOB = 'form-1004-urar-v1.pdf';

// ─── AcroForm field definitions (match FinalReportService._assembleFieldMap) ──

const FORM_FIELDS = [
  { name: 'SubjectAddress', label: 'Subject Property Address', x: 160, y: 710, w: 370, h: 14 },
  { name: 'SubjectCity',    label: 'City',                     x: 160, y: 692, w: 160, h: 14 },
  { name: 'SubjectState',   label: 'State',                    x: 335, y: 692, w:  40, h: 14 },
  { name: 'SubjectZip',     label: 'Zip',                      x: 390, y: 692, w:  80, h: 14 },
  { name: 'SubjectCounty',  label: 'County',                   x: 485, y: 692, w: 110, h: 14 },
  { name: 'BorrowerName',   label: 'Borrower Name',            x: 160, y: 670, w: 260, h: 14 },
  { name: 'BorrowerEmail',  label: 'Borrower Email',           x: 160, y: 652, w: 260, h: 14 },
  { name: 'LoanNumber',     label: 'Loan Number',              x: 160, y: 634, w: 200, h: 14 },
  { name: 'LoanAmount',     label: 'Loan Amount ($)',          x: 160, y: 616, w: 120, h: 14 },
  { name: 'LoanType',       label: 'Loan Type',                x: 340, y: 616, w: 100, h: 14 },
  { name: 'FormType',       label: 'Form / Product Type',      x: 160, y: 598, w: 160, h: 14 },
  { name: 'AppraisedValue', label: 'Appraised Value ($)',      x: 160, y: 576, w: 160, h: 14 },
  { name: 'QCScore',        label: 'QC Score (0–100)',         x: 160, y: 554, w:  80, h: 14 },
  { name: 'QCDecision',     label: 'QC Decision',              x: 300, y: 554, w: 160, h: 14 },
  { name: 'QCSummary',      label: 'QC Summary',               x: 160, y: 520, w: 380, h: 28 },
] as const;

// ─── Build AcroForm PDF ──────────────────────────────────────────────────────

async function buildAcroformPdf(): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // US Letter
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const form = pdfDoc.getForm();

  const grey = rgb(0.35, 0.35, 0.35);
  const blue = rgb(0.08, 0.24, 0.55);

  // Title block
  page.drawRectangle({ x: 30, y: 752, width: 552, height: 30, color: blue });
  page.drawText('UNIFORM RESIDENTIAL APPRAISAL REPORT  (Form 1004 — URAR)', {
    x: 40, y: 761, size: 11, font: bold, color: rgb(1, 1, 1),
  });
  page.drawText('Test Template — Generated by seed orchestrator · Appraisal Management Platform', {
    x: 40, y: 747, size: 7, font, color: grey,
  });

  // Section headers
  page.drawText('SUBJECT PROPERTY', { x: 30, y: 725, size: 8, font: bold, color: blue });
  page.drawText('BORROWER / LOAN INFORMATION', { x: 30, y: 685, size: 8, font: bold, color: blue });
  page.drawText('VALUATION & QC SUMMARY', { x: 30, y: 590, size: 8, font: bold, color: blue });

  // Separator lines
  for (const y of [748, 722, 683, 588]) {
    page.drawLine({ start: { x: 30, y }, end: { x: 582, y }, thickness: 0.5, color: rgb(0.75, 0.75, 0.75) });
  }

  // AcroForm fields
  for (const f of FORM_FIELDS) {
    page.drawText(f.label + ':', { x: 30, y: f.y + 2, size: 7, font, color: grey });
    const tf = form.createTextField(f.name);
    tf.addToPage(page, {
      x: f.x, y: f.y - 1, width: f.w, height: f.h,
      borderWidth: 0.5, borderColor: rgb(0.6, 0.6, 0.6), backgroundColor: rgb(0.97, 0.97, 1.0),
    });
    if (f.name === 'QCSummary') {
      tf.setFontSize(8);
      tf.enableMultiline();
    }
  }

  // Footer
  page.drawLine({ start: { x: 30, y: 40 }, end: { x: 582, y: 40 }, thickness: 0.5, color: grey });
  page.drawText('Machine-generated test template for development/smoke-testing only. Not for production use.', {
    x: 30, y: 28, size: 6.5, font, color: grey,
  });
  page.drawText(`Generated: ${new Date().toISOString()}`, { x: 30, y: 18, size: 6, font, color: grey });

  return pdfDoc.save();
}

// ─── Upload PDF to Blob Storage ──────────────────────────────────────────────

async function uploadTemplatePdf(storageAccountName: string, pdfBytes: Uint8Array): Promise<void> {
  const credential = new DefaultAzureCredential();
  const blobServiceClient = new BlobServiceClient(
    `https://${storageAccountName}.blob.core.windows.net`,
    credential,
  );
  const containerClient = blobServiceClient.getContainerClient(BLOB_CONTAINER);

  const exists = await containerClient.exists();
  if (!exists) {
    throw new Error(
      `Blob container '${BLOB_CONTAINER}' does not exist. ` +
      `Create it via your Bicep/infrastructure deployment before running this script.`,
    );
  }

  const blobClient = containerClient.getBlockBlobClient(TEMPLATE_BLOB);
  await blobClient.upload(pdfBytes, pdfBytes.length, {
    blobHTTPHeaders: { blobContentType: 'application/pdf', blobCacheControl: 'no-cache' },
    metadata: { generatedBy: 'seed-orchestrator', templateId: PDF_TEMPLATE_IDS.FORM_1004, formType: '1004' },
  });
  console.log(`   ✅ Uploaded ${TEMPLATE_BLOB} (${pdfBytes.length.toLocaleString()} bytes) to ${BLOB_CONTAINER}`);
}

// ─── Template metadata ───────────────────────────────────────────────────────

function buildTemplates(tenantId: string): Record<string, unknown>[] {
  return [
    {
      id: PDF_TEMPLATE_IDS.FORM_1004, tenantId, type: 'document-template',
      templateName: 'Uniform Residential Appraisal Report (Form 1004)',
      formType: '1004',
      version: '2024-01',
      status: 'ACTIVE',
      fileFormat: 'PDF_ACROFORM',
      blobPath: `templates/${tenantId}/form-1004-v2024-01.pdf`,
      blobContainer: BLOB_CONTAINER,
      blobName: TEMPLATE_BLOB,
      fieldCount: FORM_FIELDS.length,
      fieldNames: FORM_FIELDS.map(f => f.name),
      description: 'Standard Fannie Mae Form 1004 AcroForm template for residential appraisals. Contains all UAD-compliant fields for automated PDF generation.',
      supportedProducts: ['FULL_1004', 'RECERTIFICATION'],
      createdAt: daysAgo(365), updatedAt: daysAgo(90),
    },
  ];
}

export const module: SeedModule = {
  name: 'pdf-templates',
  containers: [CONTAINER],

  async run(ctx: SeedContext): Promise<SeedModuleResult> {
    const result: SeedModuleResult = { created: 0, failed: 0, skipped: 0, cleaned: 0 };

    if (ctx.clean) {
      result.cleaned = await cleanContainer(ctx, CONTAINER);
    }

    for (const tpl of buildTemplates(ctx.tenantId)) {
      await upsert(ctx, CONTAINER, tpl, result);
    }

    // Build and upload AcroForm PDF when storage account is configured
    if (ctx.storageAccountName) {
      const pdfBytes = await buildAcroformPdf();
      console.log(`   📄 Built AcroForm PDF — ${pdfBytes.length.toLocaleString()} bytes, ${FORM_FIELDS.length} fields`);
      await uploadTemplatePdf(ctx.storageAccountName, pdfBytes);
    } else {
      console.log('\n   ℹ  Blob template upload skipped (AZURE_STORAGE_ACCOUNT_NAME not set)');
    }

    return result;
  },
};
