#!/bin/bash

# Deployment Test Script
# This script validates the deployment pipeline locally

set -e

echo "🧪 Testing Appraisal Management Platform Deployment Pipeline"
echo "=============================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print status
print_status() {
    if [ $1 -eq 0 ]; then
        echo -e "${GREEN}✅ $2${NC}"
    else
        echo -e "${RED}❌ $2${NC}"
        exit 1
    fi
}

print_info() {
    echo -e "${YELLOW}ℹ️  $1${NC}"
}

# 1. Test Bicep Template Validation
echo ""
print_info "Step 1: Validating Bicep Templates"
az bicep build --file infrastructure/main-production.bicep > /dev/null 2>&1
print_status $? "Main Bicep template validation"

# Test each module
for module in infrastructure/modules/*.bicep; do
    if [ -f "$module" ]; then
        module_name=$(basename "$module")
        az bicep build --file "$module" > /dev/null 2>&1
        print_status $? "Module validation: $module_name"
    fi
done

# 2. Test Parameter Files
echo ""
print_info "Step 2: Validating Parameter Files"
for param_file in infrastructure/parameters/*.json; do
    if [ -f "$param_file" ]; then
        param_name=$(basename "$param_file")
        # Basic JSON validation
        jq empty "$param_file" > /dev/null 2>&1
        print_status $? "Parameter file validation: $param_name"
    fi
done

# 3. Test TypeScript Compilation
echo ""
print_info "Step 3: Testing TypeScript Compilation"
npm run build > /dev/null 2>&1
print_status $? "TypeScript compilation (production)"

# 4. Test Application Startup
echo ""
print_info "Step 4: Testing Application Startup"
timeout 10s node dist/app-production.js > /dev/null 2>&1 &
APP_PID=$!
sleep 3

# Check if process is still running
if kill -0 $APP_PID 2>/dev/null; then
    kill $APP_PID 2>/dev/null
    print_status 0 "Application startup test"
else
    print_status 1 "Application startup test"
fi

# 5. Test Azure CLI Authentication
echo ""
print_info "Step 5: Testing Azure CLI Authentication"
az account show > /dev/null 2>&1
print_status $? "Azure CLI authentication"

# 6. Test Deployment Validation (What-If)
echo ""
print_info "Step 6: Testing Deployment Validation (What-If)"
print_info "Testing development environment deployment..."

az deployment sub what-if \
    --location eastus2 \
    --template-file infrastructure/main-production.bicep \
    --parameters infrastructure/parameters/dev.parameters.json \
    > /dev/null 2>&1

print_status $? "Deployment what-if analysis (dev environment)"

# 7. Generate Deployment Summary
echo ""
print_info "Step 7: Generating Deployment Summary"

cat > deployment-test-results.md << EOF
# Deployment Test Results

**Test Date:** $(date)
**Branch:** $(git branch --show-current 2>/dev/null || echo "unknown")
**Commit:** $(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

## Test Results ✅

- ✅ Bicep template validation passed
- ✅ Parameter file validation passed  
- ✅ TypeScript compilation successful
- ✅ Application startup test passed
- ✅ Azure CLI authentication verified
- ✅ Deployment what-if analysis completed

## Resource Summary

### Infrastructure Components
- App Service Plan with auto-scaling
- Azure App Service with managed identity
- Cosmos DB with optimized containers
- Service Bus with event-driven queues
- Key Vault with secure secret management
- Application Insights with monitoring
- Storage Account with organized containers

### Environments
- **Development**: Basic tier, cost-optimized
- **Staging**: Standard tier, production-like
- **Production**: Premium tier, high-availability

## Next Steps

1. **Manual Deployment Test**: Run a test deployment to development environment
2. **GitHub Actions Setup**: Configure required secrets and environments
3. **Production Readiness**: Complete external API key configuration
4. **Monitoring Setup**: Configure alerts and notification channels

## Commands for Manual Deployment

\`\`\`bash
# Deploy to development environment
az deployment sub create \\
  --location eastus2 \\
  --template-file infrastructure/main-production.bicep \\
  --parameters infrastructure/parameters/dev.parameters.json

# Check deployment status
az deployment sub show \\
  --name main-production \\
  --query 'properties.provisioningState'
\`\`\`

---
*Generated by deployment test script*
EOF

print_status 0 "Deployment test summary generated"

# Final Summary
echo ""
echo "🎉 Deployment Pipeline Test Completed Successfully!"
echo ""
echo "📊 Summary:"
echo "   - All Bicep templates validated"
echo "   - TypeScript compilation successful"
echo "   - Application startup verified"
echo "   - Azure connectivity confirmed"
echo "   - Deployment validation passed"
echo ""
echo "📝 Next steps:"
echo "   1. Review deployment-test-results.md"
echo "   2. Configure GitHub Actions secrets"
echo "   3. Run a test deployment to Azure"
echo "   4. Set up monitoring and alerts"
echo ""
echo "🚀 Ready for production deployment!"
EOF